//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyBLE_MTK_Application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath1 {
            get {
                return ((string)(this["RecentPath1"]));
            }
            set {
                this["RecentPath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath2 {
            get {
                return ((string)(this["RecentPath2"]));
            }
            set {
                this["RecentPath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath3 {
            get {
                return ((string)(this["RecentPath3"]));
            }
            set {
                this["RecentPath3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath4 {
            get {
                return ((string)(this["RecentPath4"]));
            }
            set {
                this["RecentPath4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath5 {
            get {
                return ((string)(this["RecentPath5"]));
            }
            set {
                this["RecentPath5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal NumDUTs {
            get {
                return ((decimal)(this["NumDUTs"]));
            }
            set {
                this["NumDUTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Relevant")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Cypress\\\\PSoCPRoc\\\\App Log\\\\")]
        public string ApplicationLogPath {
            get {
                return ((string)(this["ApplicationLogPath"]));
            }
            set {
                this["ApplicationLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveAppLogs {
            get {
                return ((bool)(this["AutoSaveAppLogs"]));
            }
            set {
                this["AutoSaveAppLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\BLE_TestLogs\\\\")]
        public string TestLogPath {
            get {
                return ((string)(this["TestLogPath"]));
            }
            set {
                this["TestLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLogTests {
            get {
                return ((bool)(this["AutoLogTests"]));
            }
            set {
                this["AutoLogTests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUT")]
        public string AutoLogTestsSetting {
            get {
                return ((string)(this["AutoLogTestsSetting"]));
            }
            set {
                this["AutoLogTestsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTestProgDialogMsg {
            get {
                return ((bool)(this["EnableTestProgDialogMsg"]));
            }
            set {
                this["EnableTestProgDialogMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UART")]
        public string ConnectionType {
            get {
                return ((string)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PauseTestsOnFailure {
            get {
                return ((bool)(this["PauseTestsOnFailure"]));
            }
            set {
                this["PauseTestsOnFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseSerialDialog {
            get {
                return ((bool)(this["CloseSerialDialog"]));
            }
            set {
                this["CloseSerialDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAUseProgrammer {
            get {
                return ((bool)(this["BDAUseProgrammer"]));
            }
            set {
                this["BDAUseProgrammer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAIncrement {
            get {
                return ((bool)(this["BDAIncrement"]));
            }
            set {
                this["BDAIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000000000")]
        public string BDA {
            get {
                return ((string)(this["BDA"]));
            }
            set {
                this["BDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string DUTSerialPort0 {
            get {
                return ((string)(this["DUTSerialPort0"]));
            }
            set {
                this["DUTSerialPort0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM7")]
        public string DUTSerialPort1 {
            get {
                return ((string)(this["DUTSerialPort1"]));
            }
            set {
                this["DUTSerialPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM8")]
        public string DUTSerialPort2 {
            get {
                return ((string)(this["DUTSerialPort2"]));
            }
            set {
                this["DUTSerialPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM9")]
        public string DUTSerialPort3 {
            get {
                return ((string)(this["DUTSerialPort3"]));
            }
            set {
                this["DUTSerialPort3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM10")]
        public string DUTSerialPort4 {
            get {
                return ((string)(this["DUTSerialPort4"]));
            }
            set {
                this["DUTSerialPort4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM11")]
        public string DUTSerialPort5 {
            get {
                return ((string)(this["DUTSerialPort5"]));
            }
            set {
                this["DUTSerialPort5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM12")]
        public string DUTSerialPort6 {
            get {
                return ((string)(this["DUTSerialPort6"]));
            }
            set {
                this["DUTSerialPort6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM13")]
        public string DUTSerialPort7 {
            get {
                return ((string)(this["DUTSerialPort7"]));
            }
            set {
                this["DUTSerialPort7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort8 {
            get {
                return ((string)(this["DUTSerialPort8"]));
            }
            set {
                this["DUTSerialPort8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort9 {
            get {
                return ((string)(this["DUTSerialPort9"]));
            }
            set {
                this["DUTSerialPort9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort10 {
            get {
                return ((string)(this["DUTSerialPort10"]));
            }
            set {
                this["DUTSerialPort10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort11 {
            get {
                return ((string)(this["DUTSerialPort11"]));
            }
            set {
                this["DUTSerialPort11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort12 {
            get {
                return ((string)(this["DUTSerialPort12"]));
            }
            set {
                this["DUTSerialPort12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort13 {
            get {
                return ((string)(this["DUTSerialPort13"]));
            }
            set {
                this["DUTSerialPort13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort14 {
            get {
                return ((string)(this["DUTSerialPort14"]));
            }
            set {
                this["DUTSerialPort14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort15 {
            get {
                return ((string)(this["DUTSerialPort15"]));
            }
            set {
                this["DUTSerialPort15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreDUTs {
            get {
                return ((bool)(this["IgnoreDUTs"]));
            }
            set {
                this["IgnoreDUTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string MTKHostSerialPort {
            get {
                return ((string)(this["MTKHostSerialPort"]));
            }
            set {
                this["MTKHostSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnritsuSerialPort {
            get {
                return ((string)(this["AnritsuSerialPort"]));
            }
            set {
                this["AnritsuSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string DUTMultiplexerSerialPort {
            get {
                return ((string)(this["DUTMultiplexerSerialPort"]));
            }
            set {
                this["DUTMultiplexerSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AnritsuScriptID {
            get {
                return ((int)(this["AnritsuScriptID"]));
            }
            set {
                this["AnritsuScriptID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int AnritsuNumPKTS {
            get {
                return ((int)(this["AnritsuNumPKTS"]));
            }
            set {
                this["AnritsuNumPKTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configure...")]
        public string BDAProgrammerName {
            get {
                return ((string)(this["BDAProgrammerName"]));
            }
            set {
                this["BDAProgrammerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerVoltage {
            get {
                return ((string)(this["BDAProgrammerVoltage"]));
            }
            set {
                this["BDAProgrammerVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerPM {
            get {
                return ((string)(this["BDAProgrammerPM"]));
            }
            set {
                this["BDAProgrammerPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerConn {
            get {
                return ((string)(this["BDAProgrammerConn"]));
            }
            set {
                this["BDAProgrammerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerClock {
            get {
                return ((string)(this["BDAProgrammerClock"]));
            }
            set {
                this["BDAProgrammerClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerPA {
            get {
                return ((string)(this["BDAProgrammerPA"]));
            }
            set {
                this["BDAProgrammerPA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerVerify {
            get {
                return ((string)(this["BDAProgrammerVerify"]));
            }
            set {
                this["BDAProgrammerVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerHexPath {
            get {
                return ((string)(this["BDAProgrammerHexPath"]));
            }
            set {
                this["BDAProgrammerHexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAProgrammerGlobal {
            get {
                return ((bool)(this["BDAProgrammerGlobal"]));
            }
            set {
                this["BDAProgrammerGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NewLogTime {
            get {
                return ((global::System.DateTime)(this["NewLogTime"]));
            }
            set {
                this["NewLogTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TestModeLongRun {
            get {
                return ((int)(this["TestModeLongRun"]));
            }
            set {
                this["TestModeLongRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableComPortsPredefineCheck {
            get {
                return ((bool)(this["EnableComPortsPredefineCheck"]));
            }
            set {
                this["EnableComPortsPredefineCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("local")]
        public string SFCSInterface {
            get {
                return ((string)(this["SFCSInterface"]));
            }
            set {
                this["SFCSInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S001")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
            set {
                this["Site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XCccYIbhUcfqizsAH7bqrHopZ+IaovwKtbxlTfklxB4iMYecEhGm2VNCfWi7DsUCrdxMtywF8VeqL94eP" +
            "V0zaI5s6ejT5AIiqqR+twYHh2OAs88TiYPrvbk0np6ohVPX0jKo2oCM0t6/DCMb1wOPWw==")]
        public string AdoCon {
            get {
                return ((string)(this["AdoCon"]));
            }
            set {
                this["AdoCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DUTCurrentDeepSleepLimitMilliAmp {
            get {
                return ((double)(this["DUTCurrentDeepSleepLimitMilliAmp"]));
            }
            set {
                this["DUTCurrentDeepSleepLimitMilliAmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double DUTCurrentLowerLimitMilliAmp {
            get {
                return ((double)(this["DUTCurrentLowerLimitMilliAmp"]));
            }
            set {
                this["DUTCurrentLowerLimitMilliAmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DUTCurrentUpperLimitMilliAmp {
            get {
                return ((double)(this["DUTCurrentUpperLimitMilliAmp"]));
            }
            set {
                this["DUTCurrentUpperLimitMilliAmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dmm")]
        public string DMM_Alias {
            get {
                return ((string)(this["DMM_Alias"]));
            }
            set {
                this["DMM_Alias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sw")]
        public string Switch_Alias {
            get {
                return ((string)(this["Switch_Alias"]));
            }
            set {
                this["Switch_Alias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DelayInMSBeforeDUTCurrentMeasure {
            get {
                return ((int)(this["DelayInMSBeforeDUTCurrentMeasure"]));
            }
            set {
                this["DelayInMSBeforeDUTCurrentMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SamplesCountForDUTCurrentMeasure {
            get {
                return ((int)(this["SamplesCountForDUTCurrentMeasure"]));
            }
            set {
                this["SamplesCountForDUTCurrentMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSetupMTKInstrumentsInTheMTKBegin {
            get {
                return ((bool)(this["IsSetupMTKInstrumentsInTheMTKBegin"]));
            }
            set {
                this["IsSetupMTKInstrumentsInTheMTKBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALL_SAMPLES")]
        public string DUTCurrentMeasureOverallPassCondition {
            get {
                return ((string)(this["DUTCurrentMeasureOverallPassCondition"]));
            }
            set {
                this["DUTCurrentMeasureOverallPassCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IntervalBetweenDUTCurrentMeasure {
            get {
                return ((int)(this["IntervalBetweenDUTCurrentMeasure"]));
            }
            set {
                this["IntervalBetweenDUTCurrentMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mA")]
        public string DUTCurrentMeasureUnit {
            get {
                return ((string)(this["DUTCurrentMeasureUnit"]));
            }
            set {
                this["DUTCurrentMeasureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DelayPerCommandCUS_Additional {
            get {
                return ((int)(this["DelayPerCommandCUS_Additional"]));
            }
            set {
                this["DelayPerCommandCUS_Additional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CUSTestRRSRetryInTheBeginning {
            get {
                return ((int)(this["CUSTestRRSRetryInTheBeginning"]));
            }
            set {
                this["CUSTestRRSRetryInTheBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DelayPerCommandSTC_Additional {
            get {
                return ((int)(this["DelayPerCommandSTC_Additional"]));
            }
            set {
                this["DelayPerCommandSTC_Additional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int STCTestRRSRetryInTheBeginning {
            get {
                return ((int)(this["STCTestRRSRetryInTheBeginning"]));
            }
            set {
                this["STCTestRRSRetryInTheBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal RelayDelayInMS {
            get {
                return ((decimal)(this["RelayDelayInMS"]));
            }
            set {
                this["RelayDelayInMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AppAutoModeLoopWaitTime {
            get {
                return ((int)(this["AppAutoModeLoopWaitTime"]));
            }
            set {
                this["AppAutoModeLoopWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int RobotServerPort {
            get {
                return ((int)(this["RobotServerPort"]));
            }
            set {
                this["RobotServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DelayInMSAfterDUTCurrentMeasure {
            get {
                return ((int)(this["DelayInMSAfterDUTCurrentMeasure"]));
            }
            set {
                this["DelayInMSAfterDUTCurrentMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVERAGE")]
        public string DUTCurrentMeasureCriteriaPerSample {
            get {
                return ((string)(this["DUTCurrentMeasureCriteriaPerSample"]));
            }
            set {
                this["DUTCurrentMeasureCriteriaPerSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONF:CURR 1A,100uA")]
        public string DMM_ConfigCmd {
            get {
                return ((string)(this["DMM_ConfigCmd"]));
            }
            set {
                this["DMM_ConfigCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RobotAckMsgTimeoutSeconds {
            get {
                return ((int)(this["RobotAckMsgTimeoutSeconds"]));
            }
            set {
                this["RobotAckMsgTimeoutSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RobotServerDbg {
            get {
                return ((bool)(this["RobotServerDbg"]));
            }
            set {
                this["RobotServerDbg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReopenDutSerialPortIfMissing {
            get {
                return ((bool)(this["ReopenDutSerialPortIfMissing"]));
            }
            set {
                this["ReopenDutSerialPortIfMissing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralLinkSqlLocalDebug {
            get {
                return ((bool)(this["GeneralLinkSqlLocalDebug"]));
            }
            set {
                this["GeneralLinkSqlLocalDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DUTSerialNumberDuplicationCheck {
            get {
                return ((bool)(this["DUTSerialNumberDuplicationCheck"]));
            }
            set {
                this["DUTSerialNumberDuplicationCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReopenMTKHostSerialPortIfMissing {
            get {
                return ((bool)(this["ReopenMTKHostSerialPortIfMissing"]));
            }
            set {
                this["ReopenMTKHostSerialPortIfMissing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DUTModelLengthOverride {
            get {
                return ((int)(this["DUTModelLengthOverride"]));
            }
            set {
                this["DUTModelLengthOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SQLServerDataBaseEnable {
            get {
                return ((bool)(this["SQLServerDataBaseEnable"]));
            }
            set {
                this["SQLServerDataBaseEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerName"]));
            }
            set {
                this["DUTProgrammerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
  <string>5.0V</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerVoltage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerVoltage"]));
            }
            set {
                this["DUTProgrammerVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string>Reset</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerPM {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerPM"]));
            }
            set {
                this["DUTProgrammerPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerConn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerConn"]));
            }
            set {
                this["DUTProgrammerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string>1.6 MHz</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerClock {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerClock"]));
            }
            set {
                this["DUTProgrammerClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string>Program</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerPA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerPA"]));
            }
            set {
                this["DUTProgrammerPA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string>false</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerVerify {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerVerify"]));
            }
            set {
                this["DUTProgrammerVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerHexPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerHexPath"]));
            }
            set {
                this["DUTProgrammerHexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AnritsuOutputPower {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnritsuOutputPower"]));
            }
            set {
                this["AnritsuOutputPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AnritsuTXPower {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnritsuTXPower"]));
            }
            set {
                this["AnritsuTXPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Com6</string>
  <string>Com7</string>
  <string>Com8</string>
  <string>Com9</string>
  <string>Com10</string>
  <string>Com11</string>
  <string>Com12</string>
  <string>Com13</string>
  <string>Com14</string>
  <string>Com15</string>
  <string>Com16</string>
  <string>Com17</string>
  <string>Com18</string>
  <string>Com19</string>
  <string>Com20</string>
  <string>Com21</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTPredefinedSerialPorts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTPredefinedSerialPorts"]));
            }
            set {
                this["DUTPredefinedSerialPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTKTestInfo2019_R01")]
        public string SQLServerDatabaseTableName {
            get {
                return ((string)(this["SQLServerDatabaseTableName"]));
            }
            set {
                this["SQLServerDatabaseTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string DUTTestInfoRemarks {
            get {
                return ((string)(this["DUTTestInfoRemarks"]));
            }
            set {
                this["DUTTestInfoRemarks"] = value;
            }
        }
    }
}
